package util

var FuncDict map[int]string

func FuncInit() {
	FuncDict = make(map[int]string)
	FuncDict[1002] = "/sf-sys/api/system/basic/block/update"
	FuncDict[1003] = "/sf-sys/api/system/basic/mode/update"
	FuncDict[1005] = "/sf-sys/api/system/basic/safe/update"
	FuncDict[1006] = "/sf-sys/api/system/basic/https/update"
	FuncDict[1008] = "/sf-sys/api/system/basic/clock/update"
	FuncDict[1009] = "/sf-sys/api/system/basic/gateway/network/update"
	FuncDict[1010] = "/sf-sys/api/system/basic/gateway/password/update"
	FuncDict[1011] = "/sf-sys/api/system/basic/deploy/dpdk/update"
	FuncDict[1012] = "/sf-sys/api/system/user/rule/login/save"
	FuncDict[1013] = "/sf-sys/api/system/user/rule/login/delete"

	FuncDict[1014] = "/sf-plan/api/plan/plans/task/add"
	FuncDict[1015] = "/sf-plan/api/plan/plans/task/update"
	FuncDict[1016] = "/sf-plan/api/plan/plans/task/delete"

	FuncDict[1017] = "/sf-plan/api/plan/backup/delete"
	FuncDict[1018] = "/sf-plan/api/plan/backup/restore"
	FuncDict[1019] = "/sf-plan/api/plan/backup/clear"
	FuncDict[1020] = "/sf-plan/api/plan/backup/clean"
	FuncDict[1021] = "/sf-plan/api/plan/backup/logs"
	FuncDict[1022] = "/sf-plan/api/plan/backup/conf"
	FuncDict[1023] = "/sf-sys/api/system/basic/software/update"
	FuncDict[1024] = "/sf-sys/api/system/basic/license/update"
	FuncDict[1025] = "/sf-sys/api/system/basic/software/restore"
	FuncDict[1026] = "/sf-sys/api/system/basic/bypass/update"
	FuncDict[1027] = "/sf-sys/api/system/basic/flowstat/update"
	FuncDict[1028] = "/sf-sys/api/system/basic/protostat/update"
	FuncDict[1029] = "/sf-sys/api/system/basic/ts/clean"

	FuncDict[3001] = "/sf-acc/api/access/monitor/update"
	FuncDict[3002] = "/sf-acc/api/access/manage/create"
	FuncDict[3003] = "/sf-acc/api/access/manage/update"
	FuncDict[3004] = "/sf-acc/api/access/manage/delete"
	FuncDict[3005] = "/sf-acc/api/access/manage/learn"
	FuncDict[3006] = "/sf-acc/api/access/ws/manage/learn"
	FuncDict[3007] = "/sf-acc/api/access/switch/create"
	FuncDict[3008] = "/sf-acc/api/access/switch/update"
	FuncDict[3009] = "/sf-acc/api/access/switch/delete"
	FuncDict[3010] = "/sf-acc/api/access/study/update"
	FuncDict[3011] = "/sf-acc/api/access/manage/issue"
	FuncDict[3012] = "/sf-acc/api/access/switch/portsUpdate"
	FuncDict[3013] = "/sf-acc/api/access/manage/singlelearn"

	FuncDict[4001] = "/sf-pro/api/protect/address/create"
	FuncDict[4002] = "/sf-pro/api/protect/address/update"
	FuncDict[4003] = "/sf-pro/api/protect/address/delete"
	FuncDict[4004] = "/sf-pro/api/protect/address/enable"
	FuncDict[4005] = "/sf-pro/api/protect/address/disable"
	FuncDict[4006] = "/sf-pro/api/protect/service/list"
	FuncDict[4007] = "/sf-pro/api/protect/service/create"
	FuncDict[4008] = "/sf-pro/api/protect/service/update"
	FuncDict[4009] = "/sf-pro/api/protect/service/delete"
	FuncDict[4010] = "/sf-pro/api/protect/policy/create"
	FuncDict[4011] = "/sf-pro/api/protect/policy/update"
	FuncDict[4012] = "/sf-pro/api/protect/policy/delete"
	FuncDict[4013] = "/sf-pro/api/protect/policy/enable"
	FuncDict[4014] = "/sf-pro/api/protect/policy/disable"
	FuncDict[4015] = "/sf-pro/api/protect/policy/issue"
	FuncDict[4016] = "/sf-pro/api/protect/policy/sort"
}
